version: "3"
services:

  actinia:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/src/actinia-futures-plugin/.
    ports:
      - "8088:8088"
    depends_on:
      - redis
    cap_add:
      - SYS_PTRACE
    networks:
    -   actinia

  redis:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASS_FILE=/data/config/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    ports:
        - "6379:6379"
    networks:
    -   actinia

networks:
  actinia:
    ipam:
      config:
        - subnet: 172.18.0.0/16
